import { useState } from 'react'
import type { AllocationRun, Applicant, Internship } from '../types'

interface AllocationsProps {
  run: AllocationRun
  applicants: Applicant[]
  internships: Internship[]
  onRerun: () => void
}

export function Allocations({ run, applicants, internships, onRerun }: AllocationsProps) {
  const [filter, setFilter] = useState<'All' | 'Allocated' | 'Unallocated'>('All')
  const applicantOf = (id: string) => applicants.find((a) => a.id === id)
  const internshipOf = (id: string | null) => internships.find((p) => p.id === id)

  const visible = run.allocations.filter(
    (a) => filter === 'All' || a.status === filter,
  )

  return (
    <div className="view">
      <section className="panel panel-head">
        <div>
          <h3>Allocation Results</h3>
          <p className="panel-note">
            Generated by {run.engineVersion} · {new Date(run.generatedAt).toLocaleString()}.
            Every match carries an explainable reasoning string for audit.
          </p>
        </div>
        <div className="head-actions">
          <div className="seg">
            {(['All', 'Allocated', 'Unallocated'] as const).map((f) => (
              <button
                key={f}
                className={filter === f ? 'seg-on' : ''}
                onClick={() => setFilter(f)}
              >
                {f} ({run.allocations.filter((a) => f === 'All' || a.status === f).length})
              </button>
            ))}
          </div>
          <button className="btn-primary" onClick={onRerun}>
            Re-run engine
          </button>
        </div>
      </section>

      <section className="panel">
        <div className="table-wrap">
          <table className="table">
            <thead>
              <tr>
                <th>Applicant</th>
                <th>Match</th>
                <th>Score</th>
                <th>Reasoning</th>
              </tr>
            </thead>
            <tbody>
              {visible.map((al) => {
                const app = applicantOf(al.applicantId)
                const pos = internshipOf(al.internshipId)
                return (
                  <tr key={al.applicantId} className={al.status === 'Allocated' ? '' : 'row-unalloc'}>
                    <td>
                      <strong>{app?.name}</strong>
                      <div className="cell-sub">
                        {al.applicantId} · {app?.academics}% · {app?.category} · {app?.state}
                      </div>
                    </td>
                    <td>
                      {pos ? (
                        <>
                          <strong>{pos.title}</strong>
                          <div className="cell-sub">
                            {pos.id} · {pos.organization} · {pos.state}
                          </div>
                        </>
                      ) : (
                        <span className="pill pill-red">Unallocated</span>
                      )}
                    </td>
                    <td>
                      {pos ? (
                        <span className={`score score-${al.score >= 70 ? 'high' : al.score >= 50 ? 'mid' : 'low'}`}>
                          {al.score.toFixed(1)}
                        </span>
                      ) : (
                        '—'
                      )}
                    </td>
                    <td className="reasoning">{al.reasoning}</td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  )
}
